version: "3.8"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: chatbot-backend
    ports:
      - "5001:5000"
    volumes:
      - ./backend/chroma_db:/app/chroma_db
    environment:
      - PYTHONUNBUFFERED=1
      - HF_HUB_DISABLE_SSL_VERIFY=1
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - LANGSMITH_TRACING=${LANGSMITH_TRACING}
      - LANGCHAIN_TRACING_V2=true
      - LANGSMITH_ENDPOINT=${LANGSMITH_ENDPOINT}
      - LANGSMITH_API_KEY=${LANGSMITH_API_KEY}
      - LANGSMITH_PROJECT=${LANGSMITH_PROJECT}
      - JIRA_URL=${JIRA_URL}
      - JIRA_USER_EMAIL=${JIRA_USER_EMAIL}
      - JIRA_API_TOKEN=${JIRA_API_TOKEN}
    networks:
      - chatbot-network

  frontend:
    build:
      context: ./frontend-react
      dockerfile: Dockerfile
    container_name: chatbot-frontend
    ports:
      - "8501:80"
    depends_on:
      - backend
    networks:
      - chatbot-network

networks:
  chatbot-network:
    driver: bridge
